apiVersion: 'v1'
kind: 'Service'
metadata:
  name: {{ .Release.Name | squote }}
  labels:
    app: {{ .Release.Name | squote }}

spec:
  selector:
    app: {{ .Release.Name | squote }}
  ports:
    - port: 8000
      targetPort: 3000
      protocol: 'TCP'
